name: Ryan McKnight
description: Photography
markdown: kramdown 
exclude: ["scss", "Gemfile","Gemfile.lock", "README.md","config.rb"]
disqus_short_name: "Ryan McKnight"
url: http://www.mcknightstudio.com
